### PR TITLE
Create Fake Sites.md

### PR DESCRIPTION
**Pull request by Rekulous**

### CODE REVIEW

**Comment by DevShubam** [comment]
I'm not quite sure what would fit here?

**Comment by Rekulous** [comment]
> I'm not quite sure what would fit here?

Fake sites and imposter sites that are malicious and try to pretend to be other sites. This also includes typo sites that can be accidently visted such as: www.com, com.com, fake fitgirl sites, etc.

**Comment by DevShubam** [comment]
I feel like those can go into the malicious links, but I'll leave this open for the time being.

**Comment by Rekulous** [comment]
> I feel like those can go into the malicious links, but I'll leave this open for the time being.

Alright

**Comment by DevShubam** [comment]
im getting back into this project (i want it to be a smaller version of filterlists.com), so closing the pr

**Pull request closed without merging**
